
language: python
cache: apt
sudo: false
github-token: $GITHUB_TOKEN
addons:
  apt:
    packages:
    - language-pack-en-base
branches:
  only:
  - source
python:
- 3.6
install:
- pip install 'Nikola[extras]'
script:
- nikola build && nikola deploy 
notifications:
    email:
        on_success: change
        on_failure: always
