
language: python
cache: apt
sudo: false
addons:
  apt:
    packages:
    - language-pack-en-base
python:
- 3.6
install:
- pip install 'Nikola[extras]'
script:
- nikola build 
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: output
    target-branch: master
    verbose: true
    on:
        branch: master
        repo: death-of-rats/death-of-rats.github.io
