
language: python
cache: apt
sudo: false
addons:
  apt:
    packages:
    - language-pack-en-base
branches:
  only:
  - source
python:
- 3.6
install:
- pip install 'Nikola[extras]'
script:
- nikola build 
notifications:
    email:
        on_success: change
        on_failure: always
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: output
    on:
        branch: master
